// public/app/backend/design-system/ChatMessage.jsx
import React from 'react';
import PropTypes from 'prop-types';
import styled, { css } from 'styled-components';
import { colors, spacing, borderRadius, typography } from './theme';

const MessageContainer = styled.div`
  display: flex;
  gap: ${spacing.md};
  margin-bottom: ${spacing.md};
  ${({ isUser }) => isUser && css`
    flex-direction: row-reverse;
  `}
`;

const Avatar = styled.div`
  width: 40px;
  height: 40px;
  border-radius: ${borderRadius.full};
  background: ${({ isUser }) => isUser ? colors.primary.main : colors.secondary.main};
  display: flex;
  align-items: center;
  justify-content: center;
  color: ${colors.neutral.white};
  font-weight: ${typography.fontWeight.bold};
  flex-shrink: 0;
`;

const MessageContent = styled.div`
  background: ${({ isUser }) => isUser ? colors.primary.main + '15' : colors.neutral.gray[100]};
  padding: ${spacing.md};
  border-radius: ${borderRadius.lg};
  max-width: 70%;
  
  ${({ isUser }) => isUser ? css`
    border-top-right-radius: ${borderRadius.sm};
  ` : css`
    border-top-left-radius: ${borderRadius.sm};
  `}
`;

const MessageText = styled.p`
  margin: 0;
  color: ${colors.neutral.gray[900]};
  font-size: ${typography.fontSize.base};
  line-height: 1.5;
  white-space: pre-wrap;
`;

const Timestamp = styled.span`
  font-size: ${typography.fontSize.xs};
  color: ${colors.neutral.gray[500]};
  margin-top: ${spacing.xs};
  display: block;
`;

const ChatMessage = ({ message, isUser, timestamp }) => {
  return (
    <MessageContainer isUser={isUser}>
      <Avatar isUser={isUser}>
        {isUser ? 'U' : 'A'}
      </Avatar>
      <MessageContent isUser={isUser}>
        <MessageText>{message}</MessageText>
        {timestamp && <Timestamp>{timestamp}</Timestamp>}
      </MessageContent>
    </MessageContainer>
  );
};

ChatMessage.propTypes = {
  message: PropTypes.string.isRequired,
  isUser: PropTypes.bool,
  timestamp: PropTypes.string
};

export default ChatMessage;

// frontend/src/components/chat/ChatMessage.vue
<template>
  <div :class="['chat-message', { 'user-message': isUser, 'assistant-message': !isUser }]">
    <div class="message-avatar">
      <img :src="avatarSrc" :alt="isUser ? 'User Avatar' : 'Assistant Avatar'" />
    </div>
    <div class="message-content">
      <div class="message-header">
        <span class="sender-name">{{ isUser ? 'Vous' : 'Assistant' }}</span>
        <span class="message-time">{{ formatTime(timestamp) }}</span>
      </div>
      <div class="message-text" v-html="formattedContent"></div>
      <div v-if="attachments && attachments.length" class="message-attachments">
        <div v-for="attachment in attachments" :key="attachment.id" class="attachment">
          <i class="fas fa-paperclip"></i>
          <span>{{ attachment.name }}</span>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref, onMounted, watch } from 'vue'
import { formatTime, formatMessage } from '@/utils/formatters'

interface Attachment {
  id: string
  name: string
  url: string
}

interface Props {
  content: string
  isUser: boolean
  timestamp: Date
  attachments?: Attachment[]
}

const props = withDefaults(defineProps<Props>(), {
  attachments: () => []
})

const formattedContent = ref('')

const avatarSrc = computed(() => {
  return props.isUser 
    ? '/assets/user-avatar.png'
    : '/assets/assistant-avatar.png'
})

async function updateFormattedContent() {
  formattedContent.value = await formatMessage(props.content)
}

watch(() => props.content, updateFormattedContent)

onMounted(updateFormattedContent)
</script>

<style scoped lang="scss">
.chat-message {
  display: flex;
  margin: 1rem 0;
  gap: 1rem;
  
  &.user-message {
    flex-direction: row-reverse;
    
    .message-content {
      background-color: #e3f2fd;
      border-radius: 15px 15px 0 15px;
    }
  }
  
  &.assistant-message .message-content {
    background-color: #f5f5f5;
    border-radius: 15px 15px 15px 0;
  }
}

.message-avatar {
  width: 40px;
  height: 40px;
  
  img {
    width: 100%;
    height: 100%;
    border-radius: 50%;
    object-fit: cover;
  }
}

.message-content {
  padding: 1rem;
  max-width: 70%;
}

.message-header {
  display: flex;
  justify-content: space-between;
  margin-bottom: 0.5rem;
  font-size: 0.9rem;
  
  .sender-name {
    font-weight: bold;
  }
  
  .message-time {
    color: #666;
  }
}

.message-text {
  line-height: 1.5;
  white-space: pre-wrap;
}

.message-attachments {
  margin-top: 0.5rem;
  
  .attachment {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    color: #2196f3;
    font-size: 0.9rem;
    
    i {
      font-size: 1.1rem;
    }
  }
}
</style>
