// public/app/backend/design-system/Button.jsx
import React from 'react';
import styled, { css } from 'styled-components';
import { colors, typography, spacing, borderRadius, transitions } from './theme';
import PropTypes from 'prop-types';

const variants = {
  primary: css`
    background: ${colors.primary.main};
    color: ${colors.neutral.white};
    &:hover {
      background: ${colors.primary.dark};
    }
  `,
  secondary: css`
    background: ${colors.secondary.main};
    color: ${colors.neutral.white};
    &:hover {
      background: ${colors.secondary.dark};
    }
  `,
  outline: css`
    background: transparent;
    color: ${colors.primary.main};
    border: 2px solid ${colors.primary.main};
    &:hover {
      background: ${colors.primary.main}10;
    }
  `,
  text: css`
    background: transparent;
    color: ${colors.primary.main};
    &:hover {
      background: ${colors.primary.main}10;
    }
  `
};

const sizes = {
  small: css`
    padding: ${spacing.xs} ${spacing.sm};
    font-size: ${typography.fontSize.sm};
  `,
  medium: css`
    padding: ${spacing.sm} ${spacing.md};
    font-size: ${typography.fontSize.base};
  `,
  large: css`
    padding: ${spacing.md} ${spacing.lg};
    font-size: ${typography.fontSize.lg};
  `
};

const StyledButton = styled.button`
  font-family: ${typography.fontFamily.sans};
  font-weight: ${typography.fontWeight.medium};
  border-radius: ${borderRadius.md};
  border: none;
  cursor: pointer;
  transition: all ${transitions.default};
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: ${spacing.sm};
  
  ${({ variant }) => variants[variant] || variants.primary}
  ${({ size }) => sizes[size] || sizes.medium}
  
  &:disabled {
    opacity: 0.6;
    cursor: not-allowed;
  }
  
  &:focus {
    outline: none;
    box-shadow: 0 0 0 3px ${colors.primary.main}40;
  }
`;

const Button = ({ 
  children, 
  variant = 'primary', 
  size = 'medium', 
  icon,
  ...props 
}) => {
  return (
    <StyledButton variant={variant} size={size} {...props}>
      {icon && <span className="button-icon">{icon}</span>}
      {children}
    </StyledButton>
  );
};

Button.propTypes = {
  children: PropTypes.node.isRequired,
  variant: PropTypes.oneOf(['primary', 'secondary', 'outline', 'text']),
  size: PropTypes.oneOf(['small', 'medium', 'large']),
  icon: PropTypes.node,
};

export default Button;

// public/frontend/src/components/common/Button.vue
<template>
  <button 
    :class="['btn', variant, size, { disabled }]" 
    :disabled="disabled"
    @click="handleClick"
    :type="type">
    <i v-if="icon" :class="['fas', `fa-${icon}`]"></i>
    <slot></slot>
  </button>
</template>

<script>
export default {
  name: 'BaseButton',
  props: {
    variant: {
      type: String,
      default: 'primary',
      validator: value => ['primary', 'secondary', 'success', 'danger', 'warning', 'info'].includes(value)
    },
    size: {
      type: String,
      default: 'medium',
      validator: value => ['small', 'medium', 'large'].includes(value)
    },
    disabled: {
      type: Boolean,
      default: false
    },
    icon: {
      type: String,
      default: ''
    },
    type: {
      type: String,
      default: 'button',
      validator: value => ['button', 'submit', 'reset'].includes(value)
    }
  },
  emits: ['click'],
  setup(props, { emit }) {
    const handleClick = (event) => {
      if (!props.disabled) {
        emit('click', event);
      }
    };

    return {
      handleClick
    };
  }
};
</script>

<style lang="scss" scoped>
.btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  padding: 8px 16px;
  border-radius: 4px;
  border: none;
  cursor: pointer;
  font-weight: 500;
  transition: all 0.3s ease;

  i {
    font-size: 1em;
  }

  &.small {
    padding: 6px 12px;
    font-size: 0.875rem;
  }

  &.large {
    padding: 12px 24px;
    font-size: 1.125rem;
  }

  &.primary {
    background: #4CAF50;
    color: white;
    &:hover:not(.disabled) {
      background: darken(#4CAF50, 10%);
    }
  }

  &.secondary {
    background: #6c757d;
    color: white;
    &:hover:not(.disabled) {
      background: darken(#6c757d, 10%);
    }
  }

  &.success {
    background: #28a745;
    color: white;
    &:hover:not(.disabled) {
      background: darken(#28a745, 10%);
    }
  }

  &.danger {
    background: #dc3545;
    color: white;
    &:hover:not(.disabled) {
      background: darken(#dc3545, 10%);
    }
  }

  &.warning {
    background: #ffc107;
    color: #212529;
    &:hover:not(.disabled) {
      background: darken(#ffc107, 10%);
    }
  }

  &.info {
    background: #17a2b8;
    color: white;
    &:hover:not(.disabled) {
      background: darken(#17a2b8, 10%);
    }
  }

  &.disabled {
    opacity: 0.65;
    cursor: not-allowed;
    pointer-events: none;
  }
}
</style>
